ALTER TABLE "User"
ADD COLUMN "workArrangements" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "preferredLocations" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "roleFamilies" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "includedTitleTerms" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "excludedTitleTerms" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "seniorityLevels" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
